spring.application.name=community-api
spring.datasource.url=jdbc:postgresql://localhost:5432/communityDB
spring.datasource.username=postgres
spring.datasource.password=1234
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect